spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: yhp19990630
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.yhp: info
  file:
    path: log/blog-pro.log

server:
  port: 8090